import {Task} from '../models/models';

export const tasksProgress: Task[] = [
  { id: 1, status: 'progress', priority: 'high', title: 'To do test app', description: 'To do test app for company customer' },
  { id: 2, status: 'progress', priority: 'mid', title: 'Task 2', description: 'Description task 3' },
  { id: 3, status: 'progress', priority: 'low', title: 'Task 3', description: 'Description task 43246' },
  { id: 4, status: 'progress', priority: 'mid', title: 'Task 4', description: 'Description task 4' },
  { id: 5, status: 'progress', priority: 'low', title: 'Task 5', description: 'Description task 5' },
  { id: 6, status: 'progress', priority: 'high', title: 'To do test app', description: 'To do test app for company customer' },
  { id: 7, status: 'progress', priority: 'mid', title: 'Task 2', description: 'Description task 2346' },
  { id: 8, status: 'progress', priority: 'low', title: 'Task 3', description: '11111111' },
  { id: 9, status: 'progress', priority: 'mid', title: 'Task 4', description: 'Description task 4' },
  { id: 10, status: 'progress', priority: 'low', title: '22222222', description: '234234234' },
  { id: 11, status: 'progress', priority: 'high', title: '33333333', description: 'vbnvbnbnvbnvbn' },
  { id: 12, status: 'progress', priority: 'mid', title: '4444444', description: 'nnnnnnn' },
  { id: 13, status: 'progress', priority: 'low', title: '5555555', description: 'xxxxxx' },
  { id: 14, status: 'progress', priority: 'mid', title: '666665656', description: 'vvvvvv' },
  { id: 15, status: 'progress', priority: 'low', title: '04034009', description: 'nncxcvcxvxcv' },
  { id: 16, status: 'progress', priority: 'high', title: 'T123123312309', description: 'zcvxvcxvxcv' },
  { id: 17, status: 'progress', priority: 'mid', title: 'Task 2', description: '9999999999999' },
  { id: 18, status: 'progress', priority: 'low', title: 'Task 3', description: 'Description task 3' },
  { id: 19, status: 'progress', priority: 'mid', title: 'Task 4', description: 'Description task 4' },
  { id: 20, status: 'progress', priority: 'low', title: 'Task 5', description: 'Description task 5' },
  { id: 21, status: 'progress', priority: 'high', title: 'To do test app', description: 'ertertfbc b' },
  { id: 22, status: 'progress', priority: 'mid', title: 'Task 2', description: 'Description task 2' },
  { id: 23, status: 'progress', priority: 'low', title: 'Task 3', description: 'Description task 3' },
  { id: 24, status: 'progress', priority: 'mid', title: 'Task 4', description: 'Description task 4' },
  { id: 25, status: 'progress', priority: 'low', title: 'Task 5', description: 'Description task 5' },
  { id: 26, status: 'progress', priority: 'high', title: 'To do test app', description: 'To do test app for company customer' },
  { id: 27, status: 'progress', priority: 'mid', title: 'Task 2', description: 'Description task 2' },
  { id: 28, status: 'progress', priority: 'low', title: 'Task 3', description: 'Description task 3' },
  { id: 29, status: 'progress', priority: 'mid', title: 'Task 4', description: 'Description task 4' },
  { id: 30, status: 'progress', priority: 'low', title: 'Task 5', description: 'Description task 5' },
  { id: 31, status: 'progress', priority: 'high', title: 'To do test app', description: 'To do test app for company customer' },
  { id: 32, status: 'progress', priority: 'mid', title: 'Task 2', description: 'Description task 2' },
  { id: 33, status: 'progress', priority: 'low', title: 'Task 3', description: 'Description task 3' },
  { id: 34, status: 'progress', priority: 'mid', title: 'Task 4', description: 'Description task 4' },
  { id: 35, status: 'progress', priority: 'low', title: 'Task 5', description: 'Description task 5' },
  { id: 36, status: 'progress', priority: 'high', title: 'To do test app', description: 'To do test app for company customer' },
  { id: 37, status: 'progress', priority: 'mid', title: 'Task 2', description: 'Description task 2' },
  { id: 38, status: 'progress', priority: 'low', title: 'Task 3', description: 'Description task 3' },
  { id: 39, status: 'progress', priority: 'mid', title: 'Task 4', description: 'Description task 4' },
  { id: 40, status: 'progress', priority: 'low', title: 'Task 5', description: 'Description task 5' },
  { id: 41, status: 'progress', priority: 'high', title: 'To do test app', description: 'To do test app for company customer' },
  { id: 42, status: 'progress', priority: 'mid', title: 'Task 2', description: 'Description task 2' },
  { id: 43, status: 'progress', priority: 'low', title: 'Task 3', description: 'Description task 3' },
  { id: 44, status: 'progress', priority: 'mid', title: 'Task 4', description: 'Description task 4' },
  { id: 45, status: 'progress', priority: 'low', title: 'Task 5', description: 'Description task 5' },
  { id: 46, status: 'progress', priority: 'high', title: 'To do test app', description: 'To do test app for company customer' },
  { id: 47, status: 'progress', priority: 'mid', title: 'Task 2', description: 'Description task 2' },
  { id: 48, status: 'progress', priority: 'low', title: 'Task 3', description: 'Description task 3' },
  { id: 49, status: 'progress', priority: 'mid', title: 'Task 4', description: 'Description task 4' },
  { id: 50, status: 'progress', priority: 'low', title: 'Task 5', description: 'Description task 5' },
  { id: 51, status: 'progress', priority: 'high', title: 'To do test app', description: 'To do test app for company customer' },
  { id: 52, status: 'progress', priority: 'mid', title: 'Task 2', description: 'Description task 2' },
  { id: 53, status: 'progress', priority: 'low', title: 'Task 3', description: 'Description task 3' },
  { id: 54, status: 'progress', priority: 'mid', title: 'Task 4', description: 'Description task 4' },
  { id: 55, status: 'progress', priority: 'low', title: 'Task 5', description: 'Description task 5' },
  { id: 56, status: 'progress', priority: 'high', title: 'To do test app', description: 'To do test app for company customer' },
  { id: 57, status: 'progress', priority: 'mid', title: 'Task 2', description: 'Description task 2' },
  { id: 58, status: 'progress', priority: 'low', title: 'Task 3', description: 'Description task 3' },
  { id: 59, status: 'progress', priority: 'mid', title: 'Task 4', description: 'Description task 4' },
  { id: 60, status: 'progress', priority: 'low', title: 'Task 5', description: 'Description task 5' },
  { id: 61, status: 'progress', priority: 'high', title: 'To do test app', description: 'To do test app for company customer' },
  { id: 62, status: 'progress', priority: 'mid', title: 'Task 2', description: 'Description task 2' },
  { id: 63, status: 'progress', priority: 'low', title: 'Task 3', description: 'Description task 3' },
  { id: 64, status: 'progress', priority: 'mid', title: 'Task 4', description: 'Description task 4' },
  { id: 65, status: 'progress', priority: 'low', title: 'Task 5', description: 'Description task 5' },
  { id: 66, status: 'progress', priority: 'high', title: 'To do test app', description: 'To do test app for company customer' },
  { id: 67, status: 'progress', priority: 'mid', title: 'Task 2', description: 'Description task 2' },
  { id: 68, status: 'progress', priority: 'low', title: 'Task 3', description: 'Description task 3' },
  { id: 69, status: 'progress', priority: 'mid', title: 'Task 4', description: 'Description task 4' },
  { id: 70, status: 'progress', priority: 'low', title: 'Task 5', description: 'Description task 5' },
  { id: 71, status: 'progress', priority: 'mid', title: 'Task 2', description: 'Description task 2' },
  { id: 72, status: 'progress', priority: 'low', title: 'Task 3', description: 'Description task 3' },
  { id: 73, status: 'progress', priority: 'mid', title: 'Task 4', description: 'Description task 4' },
  { id: 74, status: 'progress', priority: 'low', title: 'Task 5', description: 'Description task 5' },
];

export const taskDone: Task[] = [
  { id: 1, status: 'done', priority: 'high', title: 'To do test app', description: 'To do test app for company customer' },
  { id: 2, status: 'done', priority: 'mid', title: 'Task 2', description: 'Description task 2' },
  { id: 3, status: 'done', priority: 'low', title: 'Task 3', description: 'Description task 3' },
  { id: 4, status: 'done', priority: 'mid', title: 'Task 4', description: 'Description task 4' },
  { id: 5, status: 'done', priority: 'low', title: 'Task 5', description: 'Description task 5' },
  { id: 6, status: 'done', priority: 'high', title: 'To do test app', description: 'To do test app for company customer' },
  { id: 7, status: 'done', priority: 'mid', title: 'Task 2', description: 'Description task 2' },
  { id: 8, status: 'done', priority: 'low', title: 'Task 3', description: 'Description task 3' },
  { id: 9, status: 'done', priority: 'mid', title: 'Task 4', description: 'Description task 4' },
  { id: 10, status: 'done', priority: 'low', title: 'Task 5', description: 'Description task 5' },
  { id: 11, status: 'done', priority: 'high', title: '3454345345', description: 'To do test app for company customer' },
  { id: 12, status: 'done', priority: 'mid', title: '3456346340=934', description: 'Description task 2' },
  { id: 13, status: 'done', priority: 'low', title: '1234234234', description: 'Description task 3' },
  { id: 14, status: 'done', priority: 'mid', title: '123534=03490-59', description: 'Description task 4' },
  { id: 15, status: 'done', priority: 'low', title: '2342342340-2394', description: 'Description task 5' },
  { id: 16, status: 'done', priority: 'high', title: '534985034085', description: 'To do test app for company customer' },
  { id: 17, status: 'done', priority: 'mid', title: '435934985803408958', description: 'Description task 2' },
  { id: 18, status: 'done', priority: 'low', title: '345345345345', description: 'Description task 3' },
  { id: 19, status: 'done', priority: 'mid', title: 'Task 4', description: 'Description task 4' },
  { id: 20, status: 'done', priority: 'low', title: 'Task 5', description: 'Description task 5' },
  { id: 21, status: 'done', priority: 'high', title: 'To do test app', description: 'To do test app for company customer' },
  { id: 22, status: 'done', priority: 'mid', title: 'Task 2', description: 'Description task 2' },
  { id: 23, status: 'done', priority: 'low', title: 'Task 3', description: 'Description task 3' },
  { id: 24, status: 'done', priority: 'mid', title: 'Task 4', description: 'Description task 4' },
  { id: 25, status: 'done', priority: 'low', title: 'Task 5', description: 'Description task 5' },
  { id: 26, status: 'done', priority: 'high', title: 'To do test app', description: 'To do test app for company customer' },
  { id: 27, status: 'done', priority: 'mid', title: 'Task 2', description: 'Description task 2' },
  { id: 28, status: 'done', priority: 'low', title: 'Task 3', description: 'Description task 3' },
  { id: 29, status: 'done', priority: 'mid', title: 'Task 4', description: 'Description task 4' },
  { id: 30, status: 'done', priority: 'low', title: 'Task 5', description: 'Description task 5' },
  { id: 31, status: 'done', priority: 'high', title: 'To do test app', description: 'To do test app for company customer' },
  { id: 32, status: 'done', priority: 'mid', title: 'Task 2', description: 'Description task 2' },
  { id: 33, status: 'done', priority: 'low', title: 'Task 3', description: 'Description task 3' },
  { id: 34, status: 'done', priority: 'mid', title: 'Task 4', description: 'Description task 4' },
  { id: 35, status: 'done', priority: 'low', title: 'Task 5', description: 'Description task 5' },
  { id: 36, status: 'done', priority: 'high', title: 'To do test app', description: 'To do test app for company customer' },
  { id: 37, status: 'done', priority: 'mid', title: 'Task 2', description: 'Description task 2' },
  { id: 38, status: 'done', priority: 'low', title: 'Task 3', description: 'Description task 3' },
  { id: 39, status: 'done', priority: 'mid', title: 'Task 4', description: 'Description task 4' },
  { id: 40, status: 'done', priority: 'low', title: 'Task 5', description: 'Description task 5' },
  { id: 41, status: 'done', priority: 'high', title: 'To do test app', description: 'To do test app for company customer' },
  { id: 42, status: 'done', priority: 'mid', title: 'Task 2', description: 'Description task 2' },
  { id: 43, status: 'done', priority: 'low', title: 'Task 3', description: 'Description task 3' },
  { id: 44, status: 'done', priority: 'mid', title: 'Task 4', description: 'Description task 4' },
  { id: 45, status: 'done', priority: 'low', title: 'Task 5', description: 'Description task 5' },
  { id: 46, status: 'done', priority: 'high', title: 'To do test app', description: 'To do test app for company customer' },
  { id: 47, status: 'done', priority: 'mid', title: 'Task 2', description: 'Description task 2' },
  { id: 48, status: 'done', priority: 'low', title: 'Task 3', description: 'Description task 3' },
  { id: 49, status: 'done', priority: 'mid', title: 'Task 4', description: 'Description task 4' },
  { id: 50, status: 'done', priority: 'low', title: 'Task 5', description: 'Description task 5' },
];
